# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calyptia < Formula
  desc "Calyptia Cloud CLI"
  homepage "https://github.com/calyptia/cli"
  version "0.32.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/calyptia/cli/releases/download/v0.32.4/cli_0.32.4_darwin_arm64.tar.gz"
      sha256 "bd20eb8b9af371a949d37785001fba5aa2ffc9cef2eef88be1bfaba20e468f21"

      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/calyptia/cli/releases/download/v0.32.4/cli_0.32.4_darwin_amd64.tar.gz"
      sha256 "1128eeb2a43e510478a42f4890c7be188f34e6744d5f8df9d422a9dd3418908b"

      def install
        bin.install "calyptia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/calyptia/cli/releases/download/v0.32.4/cli_0.32.4_linux_amd64.tar.gz"
      sha256 "81332466efb3de1239fe4b2cd8f2edaf26777ca8b3408740afde51762056e3a3"

      def install
        bin.install "calyptia"
      end
    end
  end
end
