# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3700 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.70.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.70.0/calyptia-cli_3.70.0_darwin_all.tar.gz"
    sha256 "1376ad02206fe2cc7dc49d585533f529186671f4382e615319d3749a8bda9a82"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.70.0/calyptia-cli_3.70.0_linux_amd64.tar.gz"
      sha256 "ed3f3e737200065cd8e8d43cc702052309fd6a417b75098f9f64a491d8f242c2"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.70.0/calyptia-cli_3.70.0_linux_arm64.tar.gz"
      sha256 "881a2f5e0f4f9ca338d7ba0ab2e2d444496a8168bda3ce70064f465ba1afec76"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
