# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT31020 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.102.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.102.0/calyptia-cli_3.102.0_darwin_all.tar.gz"
    sha256 "dd9064ffbda2d37b06c758860d8a49c832ed97f3c6f2985f0f330cd19ed6025f"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.102.0/calyptia-cli_3.102.0_linux_amd64.tar.gz"
      sha256 "d03d4fd495cbadd00259d1ae6ff68faba6a047951a602ef54ff624cd96516f24"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.102.0/calyptia-cli_3.102.0_linux_arm64.tar.gz"
      sha256 "f10d294b05cfd9cd1553ffb90200874838e928ebdb6ad9feddf272f1d40f8a00"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
