# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3580 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.58.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.58.0/calyptia-cli_3.58.0_darwin_all.tar.gz"
    sha256 "a41d939fcab0330d729ec21d255d75fe874e7f472481aee6c42d6c1cd8ffa2d0"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.58.0/calyptia-cli_3.58.0_linux_amd64.tar.gz"
      sha256 "9e118c7b7b986615c80d68cbecda1b09c03340a36ea373240d0cab7e1a5f7bf7"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.58.0/calyptia-cli_3.58.0_linux_arm64.tar.gz"
      sha256 "279f1d52d324d73513dbcedf4103f4d2ed0b297fbfe5c44b51d62fb64a075223"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
