# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.57.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.57.0/calyptia-cli_3.57.0_darwin_all.tar.gz"
    sha256 "74ff9bfec6005252120676373a6c38909e6b8ef41242cd3550d7c4cf0bf494c7"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.57.0/calyptia-cli_3.57.0_linux_amd64.tar.gz"
      sha256 "9dec8f84e82d32205d471093f915ca4f539301fd367ceb22cbee3538dee12684"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.57.0/calyptia-cli_3.57.0_linux_arm64.tar.gz"
      sha256 "3d4e1a59de43f2a38f06724b2c00c538d5834da223fda60eb25a39e3ff3ae589"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
