# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3620 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.62.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.62.0/calyptia-cli_3.62.0_darwin_all.tar.gz"
    sha256 "d452126869dacb9d5482d10fd4c5cafc759ae8af58a78b05cbd42dd52b8b50b2"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.62.0/calyptia-cli_3.62.0_linux_amd64.tar.gz"
      sha256 "b992ad696c9fb18d6b340a36806722b179223218219549d8fd6bfe3dd59d8839"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.62.0/calyptia-cli_3.62.0_linux_arm64.tar.gz"
      sha256 "5258f4f816955f4bee784950d5ce82318fc317ade45b7b085c3241dde5e1d942"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
