# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3960 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.96.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.96.0/calyptia-cli_3.96.0_darwin_all.tar.gz"
    sha256 "802a2512268c1fdd8fe9fbdafc3983248277ff0e408fa030673e698695709dd4"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.96.0/calyptia-cli_3.96.0_linux_amd64.tar.gz"
      sha256 "6ef29b13e8d69d135fae5162cccd4175fdcdf2fa7bfdb5934ea7a10cf6adddb2"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.96.0/calyptia-cli_3.96.0_linux_arm64.tar.gz"
      sha256 "c6f20ea5d501fcf9d30e31d004b51b6de243bac590c58f418c6117d29f3872ee"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
