# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3360 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.36.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.36.0/calyptia-cli_3.36.0_darwin_all.tar.gz"
    sha256 "7c2f2d608cabef74b09958c45cae7806258101a2def3942e19bcf85268d58bc6"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.36.0/calyptia-cli_3.36.0_linux_amd64.tar.gz"
        sha256 "b04a947326530171180aa1d771f1438f1edbec580d7ad91b453b62648d5b9324"

        def install
          bin.install "calyptia"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.36.0/calyptia-cli_3.36.0_linux_arm64.tar.gz"
        sha256 "bb5fb08fa76b37ae8b6037baafffe5527440e22909c4a06538fa4f67d76e1227"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
