# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3930 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.93.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.93.0/calyptia-cli_3.93.0_darwin_all.tar.gz"
    sha256 "9fa9b7df0173390d38f18b5a1e422caadb8874b99739bf671a6939cd2137449d"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.93.0/calyptia-cli_3.93.0_linux_amd64.tar.gz"
      sha256 "afc15f5f27342625b7c0c45cabed777c54a3a16a0a7025a3552cd9101b3e96a4"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.93.0/calyptia-cli_3.93.0_linux_arm64.tar.gz"
      sha256 "61fb58692e6f489d379492e75fd64d668f6cd01cacab1fa48eacce9464f43949"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
