# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calyptia < Formula
  desc "Calyptia Cloud CLI"
  homepage "https://github.com/calyptia/cli"
  version "1.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/calyptia/cli/releases/download/v1.7.0/cli_1.7.0_darwin_arm64.tar.gz"
      sha256 "132ebcc7c51ca19dfc1a1b1023aa30ac10fa256c64825db7fb27beebe391a529"

      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/calyptia/cli/releases/download/v1.7.0/cli_1.7.0_darwin_amd64.tar.gz"
      sha256 "a6b1fa2bb42b83571344d9c9dd6a96df26619b3eddfb13f1d7ca9a7cffa1b005"

      def install
        bin.install "calyptia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/calyptia/cli/releases/download/v1.7.0/cli_1.7.0_linux_amd64.tar.gz"
      sha256 "9e6f7d019d5eb5278c199f7841e5f48f564fa936f7f695179e2614497d300a1f"

      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/calyptia/cli/releases/download/v1.7.0/cli_1.7.0_linux_arm64.tar.gz"
      sha256 "0d573ae68bba43a53300e9e4c7ab00df47b89af040bc1d36e4c1e25582d3f363"

      def install
        bin.install "calyptia"
      end
    end
  end
end
