# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3730 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.73.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.73.0/calyptia-cli_3.73.0_darwin_all.tar.gz"
    sha256 "a021c0f623617578180cb6492bbf0e1a63e24cdcc161c1214fddfee6d197fda4"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.73.0/calyptia-cli_3.73.0_linux_amd64.tar.gz"
      sha256 "5b88741940af720a31c3abc4db274c91dbdeb76e03461133cb5c3061751542b4"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.73.0/calyptia-cli_3.73.0_linux_arm64.tar.gz"
      sha256 "05e547f43193b03cf335f4ba054d4b960417d01173027b8f5fa23bb195840d55"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
