# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3590 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.59.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.59.0/calyptia-cli_3.59.0_darwin_all.tar.gz"
    sha256 "23d7910b415a57b1f0310729e2392be712f92855e6d65c7e0ba94784bc55a945"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.59.0/calyptia-cli_3.59.0_linux_amd64.tar.gz"
      sha256 "7d78e7804592a578b3ffbf97b1031438244a52bde9b6ccf9d59308cf8058cc34"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.59.0/calyptia-cli_3.59.0_linux_arm64.tar.gz"
      sha256 "ed8090eab15d402e8de8637c7e719ace7c08c9afe1cf7e98051fd304537799ff"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
