# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3300 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.30.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.30.0/calyptia-cli_3.30.0_darwin_all.tar.gz"
    sha256 "d1ea1a0735fa298e8b13a15975bf92762030f963692e12961659461214c2e70d"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.30.0/calyptia-cli_3.30.0_linux_amd64.tar.gz"
        sha256 "1356c4a521b7db1006f39caafdec760d5173203aa62681782dda6ca36efe245d"

        def install
          bin.install "calyptia"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.30.0/calyptia-cli_3.30.0_linux_arm64.tar.gz"
        sha256 "6cffdafb909a5820cbc1e4609f013043718683462160e97346d864564b709bd9"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
