# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT320 < Formula
  desc "Calyptia Cloud CLI"
  homepage "https://github.com/chronosphereio/calyptia-cli"
  version "3.2.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.2.0/calyptia-cli_3.2.0_darwin_all.tar.gz"
    sha256 "d224fa0c25bca15d0b5323985905151af31e6a6558d2c1da8b693d9cb04b4fe2"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.2.0/calyptia-cli_3.2.0_linux_amd64.tar.gz"
        sha256 "8f5d9edb75d533e62f8c35cb162c6851901013a068a7c0ff438293e74bc867b4"

        def install
          bin.install "calyptia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.2.0/calyptia-cli_3.2.0_linux_arm64.tar.gz"
        sha256 "92e17637f3f1fcf5085c8a219e6cdd8870b8b17c31e6725f3a6bba5e2337c1e3"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
