# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3550 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.55.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.55.0/calyptia-cli_3.55.0_darwin_all.tar.gz"
    sha256 "a71348c12f36482560baf930b5865a942a84aec670fd772d209e79d85c9f899b"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.55.0/calyptia-cli_3.55.0_linux_amd64.tar.gz"
      sha256 "9f41ba4b576eecd24fea24d4b94330f2f63437086d7f95e758b2d4c856278ffe"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.55.0/calyptia-cli_3.55.0_linux_arm64.tar.gz"
      sha256 "56cf5b064036265d48b95166758d37e4ce07bb488eaa55c7fb5095934521baae"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
