# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT360 < Formula
  desc "Calyptia Cloud CLI"
  homepage "https://github.com/chronosphereio/calyptia-cli"
  version "3.6.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.6.0/calyptia-cli_3.6.0_darwin_all.tar.gz"
    sha256 "119ac420015eb8af5eac21f6d82100332c5673c0d3bba68ae5f8d7d1eebb0253"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.6.0/calyptia-cli_3.6.0_linux_amd64.tar.gz"
        sha256 "ad095386fcc0c2766efc01f1e5e8866e9fa9d566033c5d237c399395f68cb921"

        def install
          bin.install "calyptia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.6.0/calyptia-cli_3.6.0_linux_arm64.tar.gz"
        sha256 "c73c74e6b14a5505a1a8730e241fbe0b6d6360dbde2554c25aa2b96c362f11da"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
