# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3900 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.90.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.90.0/calyptia-cli_3.90.0_darwin_all.tar.gz"
    sha256 "d6ac1dd157fab876c04aeac0ac2f5d564b9715ad6bcc345ec87939970bf6037e"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.90.0/calyptia-cli_3.90.0_linux_amd64.tar.gz"
      sha256 "004b477909bf7809a383130990a73633873b4d8942af453b7d2976ba87d1b083"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.90.0/calyptia-cli_3.90.0_linux_arm64.tar.gz"
      sha256 "9b20d16e041425306da79d083d765fd7991728d02da9c01737d6e54332acd5c0"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
