# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3670 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.67.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.67.0/calyptia-cli_3.67.0_darwin_all.tar.gz"
    sha256 "71df459d1d00df352f614a7fd140d83a2ff44b518b187b4528ba2565985a5da2"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.67.0/calyptia-cli_3.67.0_linux_amd64.tar.gz"
      sha256 "d4b2e847cb5eb6bb1dd732f6d1f8e2cd80d640f22e7dfe04ecbfc29a05fd4807"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.67.0/calyptia-cli_3.67.0_linux_arm64.tar.gz"
      sha256 "c85241a47680066f899f3dad019e69c90e85df1d7680184598578a73ad0f70b2"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
