# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3770 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.77.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.77.0/calyptia-cli_3.77.0_darwin_all.tar.gz"
    sha256 "9dcf87326dc95273aea1685d78c74824825f4c6c176f0840e193c679b57d3ced"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.77.0/calyptia-cli_3.77.0_linux_amd64.tar.gz"
      sha256 "3b5e8c9874a1d1b3d47d101b5eece04f2ce8bb4725b2007eac61badf082c9ae5"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.77.0/calyptia-cli_3.77.0_linux_arm64.tar.gz"
      sha256 "0c6b550fa69a3c2a3deb116360ceeec335b4934f2103af3ebcf0d404504cceac"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
