# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3460 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.46.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.46.0/calyptia-cli_3.46.0_darwin_all.tar.gz"
    sha256 "df4c685cf523ef948d117db4fe056529c522cac7dfc01ca7f2d9abd9d68316a5"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.46.0/calyptia-cli_3.46.0_linux_amd64.tar.gz"
      sha256 "ad03644e75713b3f9e74a1f5f4a867c44cb387e9be74311fd358112d90d8476d"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.46.0/calyptia-cli_3.46.0_linux_arm64.tar.gz"
      sha256 "f377d8869b1bb44a78dd12ba082cc34cdaf0f675db4134267158a93202270454"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
