# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3440 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.44.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.44.0/calyptia-cli_3.44.0_darwin_all.tar.gz"
    sha256 "28304532c57ee6be4fca6896defb2c639f0e77c1ac74b8249fadc5572e853d71"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.44.0/calyptia-cli_3.44.0_linux_amd64.tar.gz"
      sha256 "576a3fb1c81fb30bc09fd09c4914ca3a6b65f5c7c7b8eae9360f31b874a235dc"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.44.0/calyptia-cli_3.44.0_linux_arm64.tar.gz"
      sha256 "8f4bc7cbaafee8cbf58ab4aaa2fdd52b519fb4af8e6b9d30f9a3acc16d176a60"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
