# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT31150 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.115.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.115.0/calyptia-cli_3.115.0_darwin_all.tar.gz"
    sha256 "73b8892eb9f201b80d57ea768d6721702cc5de5802540541333a5e2bd1ecd219"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.115.0/calyptia-cli_3.115.0_linux_amd64.tar.gz"
      sha256 "2c04a8bd369274f7f19b55cc20854b9cbd11eaa9e3e0ef52e6162c962f0ce9e0"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.115.0/calyptia-cli_3.115.0_linux_arm64.tar.gz"
      sha256 "d8c33ce919f5c05e886b27b7bd712ab60b9b5e33232858c62067a850c98d0762"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
