# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT31190 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.119.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.119.0/calyptia-cli_3.119.0_darwin_all.tar.gz"
    sha256 "d2318b93f505081378c4c39ffdcba60fecb8fe19fbfb9364b8e3e212e429bb5d"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.119.0/calyptia-cli_3.119.0_linux_amd64.tar.gz"
      sha256 "1031950e56873c9a521cbbe41303b26e5a0babb704d040ebdc64cbf7a3cf3123"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.119.0/calyptia-cli_3.119.0_linux_arm64.tar.gz"
      sha256 "f48ed4d03d794a0a69f5d040c9b5d48a97ea82afe9a43306013513381e9f266a"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
