# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3980 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.98.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.98.0/calyptia-cli_3.98.0_darwin_all.tar.gz"
    sha256 "63187064ee0fc1c1559b9ec9d18347a4ee2e24b2e9d770c6ac194e3dbb0bc752"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.98.0/calyptia-cli_3.98.0_linux_amd64.tar.gz"
      sha256 "375a349f874dd998042e6e055b51066b0c5a7136b7418f3c4e8f7fc83f4d025e"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.98.0/calyptia-cli_3.98.0_linux_arm64.tar.gz"
      sha256 "14cb78b3c74a4c72fff70da6d65fad4daf32ca53254eb71ad32142d6bf81e387"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
