# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT31050 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.105.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.105.0/calyptia-cli_3.105.0_darwin_all.tar.gz"
    sha256 "7efa3249a41df1dcd8f8c3ebc79d2d5783d90aa6192d542068928a22ad5715b6"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.105.0/calyptia-cli_3.105.0_linux_amd64.tar.gz"
      sha256 "d17fe8353db2a0a7905bbc4d0f7ff0c99876daae7c100ec6335078311d2dcfb4"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.105.0/calyptia-cli_3.105.0_linux_arm64.tar.gz"
      sha256 "8aec120612cbd709d53e5b11aa502462d8306c2f8fd6f8a5ae4d542dab7ddeb9"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
