# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3920 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.92.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.92.0/calyptia-cli_3.92.0_darwin_all.tar.gz"
    sha256 "8d38504275f0762ba07f40fd4428fb689a4a50f3f4a19e7a934df6ba8b30789e"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.92.0/calyptia-cli_3.92.0_linux_amd64.tar.gz"
      sha256 "cd7c66320a6de6865eec408eb38c3f9cbe434529f51789d78fa8981012bd2979"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.92.0/calyptia-cli_3.92.0_linux_arm64.tar.gz"
      sha256 "ef9f6fc2e3c4bfa3dd03e1bcd5a877bd53626d0b6c2d9f9db93959045b19ed46"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
