# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT1184 < Formula
  desc "Calyptia Cloud CLI"
  homepage "https://github.com/chronosphereio/calyptia-cli"
  version "1.18.4"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.18.4/calyptia-cli_1.18.4_darwin_all.tar.gz"
    sha256 "48a05894d4a7e41a520551ff2570ca7d27dccedb62071e3c65e7599b34c835cb"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.18.4/calyptia-cli_1.18.4_linux_amd64.tar.gz"
        sha256 "4613aa8973daabe9c89497954afa3578c7d5ca11cc9d77d28559f655489ee0bf"

        def install
          bin.install "calyptia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.18.4/calyptia-cli_1.18.4_linux_arm64.tar.gz"
        sha256 "ecad5d5bfafb5dbe93ea062cf92ca1de3e6fdf3cd6840889d88971f7fdfe6dad"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
