# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT1194 < Formula
  desc "Calyptia Cloud CLI"
  homepage "https://github.com/chronosphereio/calyptia-cli"
  version "1.19.4"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.19.4/calyptia-cli_1.19.4_darwin_all.tar.gz"
    sha256 "8ab244cb16c940754a1066ede62945ade4236f40793432bf3fec7b0004e979ef"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.19.4/calyptia-cli_1.19.4_linux_amd64.tar.gz"
        sha256 "638070f28ba20d1d05ba4e1e317fb3d0e55d9075c8751a09a27c6f3c24721405"

        def install
          bin.install "calyptia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.19.4/calyptia-cli_1.19.4_linux_arm64.tar.gz"
        sha256 "504b357420068ce97265a6ff4437325740b3cea09b352cdc36445973c1107446"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
