# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT1200 < Formula
  desc "Calyptia Cloud CLI"
  homepage "https://github.com/chronosphereio/calyptia-cli"
  version "1.20.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.20.0/calyptia-cli_1.20.0_darwin_all.tar.gz"
    sha256 "0c310999921418e7f084c28855778b33f78dc0da028769effe6a2cade6313bb4"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.20.0/calyptia-cli_1.20.0_linux_amd64.tar.gz"
        sha256 "7059d5319df670113185a72ea04ea4c9a4b9f68fa11da799782a1b0732320450"

        def install
          bin.install "calyptia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.20.0/calyptia-cli_1.20.0_linux_arm64.tar.gz"
        sha256 "da82d9f167e4af250ebf759289618a54e18857a53124826986342aef27c0a0d7"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
