# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3410 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.41.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.41.0/calyptia-cli_3.41.0_darwin_all.tar.gz"
    sha256 "3bb53bf9dc60a7b9281dff50f8a2580a7fa9c8303b5c1d422a6abad9c4d2046d"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.41.0/calyptia-cli_3.41.0_linux_amd64.tar.gz"
        sha256 "60a437af069208d172209b036a963d8aa6199cad243a6dd9b75f49512ddec58c"

        def install
          bin.install "calyptia"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.41.0/calyptia-cli_3.41.0_linux_arm64.tar.gz"
        sha256 "62f2abb2782bfc94d8a2379bf5771b79959534fec3b58b5f82a85b8cdfe24416"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
