# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT31120 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.112.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.112.0/calyptia-cli_3.112.0_darwin_all.tar.gz"
    sha256 "4f4ceaff95c7ccb02b02d66e9a3e5acdc0a2cda9bd5632bc68684d2ffebc3ba0"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.112.0/calyptia-cli_3.112.0_linux_amd64.tar.gz"
      sha256 "eea480bc8f6bc4799c578da1d65f53c7e9bda3b4ca264e8ebe9b62b23a500fcd"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.112.0/calyptia-cli_3.112.0_linux_arm64.tar.gz"
      sha256 "5384edc147537b2f5e180eff52ba50e65424a36ed818c80366537aab3dadadeb"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
