# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT31110 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.111.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.111.0/calyptia-cli_3.111.0_darwin_all.tar.gz"
    sha256 "bcb8a3e237b92d2f5dbd55418710f7e8be8bbbf9eaad448b4bf4c5e8ca3f8b7d"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.111.0/calyptia-cli_3.111.0_linux_amd64.tar.gz"
      sha256 "07398fcc1b49287c26020e21edeb15b2959849f8f71af180c55e294856b05844"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.111.0/calyptia-cli_3.111.0_linux_arm64.tar.gz"
      sha256 "d1b202772d084aaf5ece29162992078e6c27df33d13328d25bd79ffb6c7513e4"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
