# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT31130 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.113.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.113.0/calyptia-cli_3.113.0_darwin_all.tar.gz"
    sha256 "3a02741099c94678085eb34cc4118580047d44b0862f6ecf83b1b8996396cbf2"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.113.0/calyptia-cli_3.113.0_linux_amd64.tar.gz"
      sha256 "83fa5f12555e85854f8bf0ccab64efde10ca8f66fb3262a167f12ae8926bfaea"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.113.0/calyptia-cli_3.113.0_linux_arm64.tar.gz"
      sha256 "9baa4b2e80c36bab7dd30d1e67ff1b6a97a62fef34890c5db7e0d40b4ecef8ea"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
