# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT301 < Formula
  desc "Calyptia Cloud CLI"
  homepage "https://github.com/chronosphereio/calyptia-cli"
  version "3.0.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-backend/releases/download/v3.0.1/calyptia-backend_3.0.1_darwin_all.tar.gz"
    sha256 "d5403b97261d9de4bc2fc044a80de4eea16eacbd1a44b41b212326ee7a09af54"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-backend/releases/download/v3.0.1/calyptia-backend_3.0.1_linux_amd64.tar.gz"
        sha256 "abdfd4c428a2fad5937eeab09e29d72d89c2f634a640c45f4903eadb3732f5e6"

        def install
          bin.install "calyptia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-backend/releases/download/v3.0.1/calyptia-backend_3.0.1_linux_arm64.tar.gz"
        sha256 "b088d281c62aba4b2015029e75b15473de4c7f3e692b055a53c85cc0e482ef61"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
