# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT1 < Formula
  desc "Calyptia Cloud CLI"
  homepage "https://github.com/chronosphereio/calyptia-cli"
  version "1.19.3"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.19.3/calyptia-cli_1.19.3_darwin_all.tar.gz"
    sha256 "7417b4cd79af3d3066627a6faa21fc635158c9b45564e63cbdb166191ba713b2"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.19.3/calyptia-cli_1.19.3_linux_amd64.tar.gz"
        sha256 "2dd74618250d3e781ff3be77f24c6353ee42f28e2f65a0ee9f0455c45d9ae32e"

        def install
          bin.install "calyptia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v1.19.3/calyptia-cli_1.19.3_linux_arm64.tar.gz"
        sha256 "5770b1a5bd8c7b9f362af2e58f8bfe16b9e5145c1d3a08dcb23f7cc574fe4cb8"

        def install
          bin.install "calyptia"
        end
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
