# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT3570 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.57.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.57.0/calyptia-cli_3.57.0_darwin_all.tar.gz"
    sha256 "1ae0d48d895aa14320f6d5c25d0a4fd89ccbee4ce87bd07b280e09717a509f9b"

    def install
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.57.0/calyptia-cli_3.57.0_linux_amd64.tar.gz"
      sha256 "8b080832b05c3b9d0181bb0a97666e2bf54f4cd03641e32620376cc91bd3defb"
      def install
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.57.0/calyptia-cli_3.57.0_linux_arm64.tar.gz"
      sha256 "83eb90086531353d2d1facd0dfc37c0ef4a1ec8fd93794f0beed48d39a65c840"
      def install
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
