# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CalyptiaAT31070 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.107.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.107.0/calyptia-cli_3.107.0_darwin_all.tar.gz"
    sha256 "e40caffff63245d09faaf79cd5dc68c72724efca710b3117b3c7fc1f13318fd7"

    define_method(:install) do
      bin.install "calyptia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.107.0/calyptia-cli_3.107.0_linux_amd64.tar.gz"
      sha256 "a429b2c24bcfc0763393afeeeac3d81542c3654b09292847f40a60a37f9a9487"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.107.0/calyptia-cli_3.107.0_linux_arm64.tar.gz"
      sha256 "30cb16a7e09f23a60ea4f65004d739e9bbf919609f514960139bab850cd97d4f"
      define_method(:install) do
        bin.install "calyptia"
      end
    end
  end

  test do
    system "#{bin}/calyptia version"
  end
end
