# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3420 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.42.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.42.0/pipelinectl_3.42.0_darwin_all.tar.gz"
    sha256 "2fd5ead146aa5cac71a17a8c2fdadac06deefd9ebbe5a83840cd9e9778b3f82c"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.42.0/pipelinectl_3.42.0_linux_amd64.tar.gz"
        sha256 "47458eab01d33faba777002ce4935d21978ba4207e799971103eb2ea0c51f932"

        def install
          bin.install "pipelinectl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.42.0/pipelinectl_3.42.0_linux_arm64.tar.gz"
        sha256 "eb000d1e98a0102a6b87a9f4b0435ab64d828b2b25d61927940619f253f14080"

        def install
          bin.install "pipelinectl"
        end
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
