# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3400 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.40.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.40.0/pipelinectl_3.40.0_darwin_all.tar.gz"
    sha256 "eec0730c19afa68159efa4e9cd00e009489678fedefac12a14f531718fdc1ca1"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.40.0/pipelinectl_3.40.0_linux_amd64.tar.gz"
        sha256 "43c30f7cca0abd7f019aba394fc99bcd2ef1c5945cce39b47a8e0501a48e5b8c"

        def install
          bin.install "pipelinectl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.40.0/pipelinectl_3.40.0_linux_arm64.tar.gz"
        sha256 "c1544247870d7b390418e4676c6cc2f65df06dbddd0a25738df52ed5630a494b"

        def install
          bin.install "pipelinectl"
        end
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
