# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipelinectl < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.58.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.58.0/pipelinectl_3.58.0_darwin_all.tar.gz"
    sha256 "f83e5a936bb5761ecb8b0ac22913aadd8ab820a6f8de488eb3eec413e7f07bd4"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.58.0/pipelinectl_3.58.0_linux_amd64.tar.gz"
      sha256 "4a5e062e6d61172cfc63bd0bd26c370298abf79d0d481c9b034ce1724c217b61"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.58.0/pipelinectl_3.58.0_linux_arm64.tar.gz"
      sha256 "5fef15ba07067d1bed738d16922e59deba8b8372db6c5f8e6bcd8e43ed698c58"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
