# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3600 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.60.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.60.0/pipelinectl_3.60.0_darwin_all.tar.gz"
    sha256 "75c1ce5e431d98545662cf1ba445b7e5049c09c67de63db5108cb95d1980a439"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.60.0/pipelinectl_3.60.0_linux_amd64.tar.gz"
      sha256 "741596efba696a07b3a86fc0a0d1acee84b0fd5efa5ba507d62fba2d0056b55c"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.60.0/pipelinectl_3.60.0_linux_arm64.tar.gz"
      sha256 "697be7faa4b37bca6487401df8c561f12fbb682b8f3cf9ce36a02b81ab68b872"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
