# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3270 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.27.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.27.0/pipelinectl_3.27.0_darwin_all.tar.gz"
    sha256 "b263c17e22806dbeb4a14fa266150deafcbadb4f597bb9edfd608b2a5f179e04"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.27.0/pipelinectl_3.27.0_linux_amd64.tar.gz"
        sha256 "2b990336f7c0fb1afa7c475b4054bd84e14b1b5bf21b45b0409c69b15f0a493e"

        def install
          bin.install "pipelinectl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.27.0/pipelinectl_3.27.0_linux_arm64.tar.gz"
        sha256 "27113c2e4f014dc1f6127aa5ed64b42ad8c7c32848ca29741c285d9c9bc80932"

        def install
          bin.install "pipelinectl"
        end
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
