# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipelinectl < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.66.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.66.0/pipelinectl_3.66.0_darwin_all.tar.gz"
    sha256 "3f8a791a4c2b4f3643be4cf50be733ef34d56d3f1f2c43f774d2fe6728f1b4fe"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.66.0/pipelinectl_3.66.0_linux_amd64.tar.gz"
      sha256 "5b25bc92b1d64ca70451c6fdee451e53072d67b9e3d505e4731fcb82871c005b"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.66.0/pipelinectl_3.66.0_linux_arm64.tar.gz"
      sha256 "0c9c642bf629f64676788ac5e303726a30a84f3dc8625fe8f15fe0ba586aac2a"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
