# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3650 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.65.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.65.0/pipelinectl_3.65.0_darwin_all.tar.gz"
    sha256 "2087ac474a562d8ae07a2387a5b368cc29505bc858ae191b4b8b70450e2a07a7"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.65.0/pipelinectl_3.65.0_linux_amd64.tar.gz"
      sha256 "3021e54ac6d862b056da1d32f5e7a8a3e3073e383f5ce533ae10495a701fd305"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.65.0/pipelinectl_3.65.0_linux_arm64.tar.gz"
      sha256 "76c89f1d609749c342724d5c429dc1c23e9f6c92f1d4091b497a37a41d5b5faa"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
