# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.33.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.33.0/pipelinectl_3.33.0_darwin_all.tar.gz"
    sha256 "3f380e30aeee308aadb3ded94c27bbb7fe99f95361cdb1d3cca5da7d18f7d096"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.33.0/pipelinectl_3.33.0_linux_amd64.tar.gz"
        sha256 "05f5abfc23044ebce4aef034aedc9ed87acbcb0dbbafe8ea518089d7962e3b60"

        def install
          bin.install "pipelinectl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.33.0/pipelinectl_3.33.0_linux_arm64.tar.gz"
        sha256 "ff28079fef9b4e1fd85a927afc80fc2b23e96d055e7db7d43bec4c9b51cc343a"

        def install
          bin.install "pipelinectl"
        end
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
