# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3610 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.61.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.61.0/pipelinectl_3.61.0_darwin_all.tar.gz"
    sha256 "f23c7279cee0d09ef112e9a4735cdd75fdf456e38e3dc8b04cc043d766503aeb"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.61.0/pipelinectl_3.61.0_linux_amd64.tar.gz"
      sha256 "0850c927d91609512d97c1b2f969ee909bf26580e3dca5392c79cd020b141005"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.61.0/pipelinectl_3.61.0_linux_arm64.tar.gz"
      sha256 "e7590937026aadfc59eaa69a60b75c4ef246d9a2cd4683da47dd0a11ac3d8cc4"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
