# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.47.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.47.0/pipelinectl_3.47.0_darwin_all.tar.gz"
    sha256 "08fa2c79422fe44b021e7fdd64487d8a2627661bf5c60edac7dd1a4644ed622c"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.47.0/pipelinectl_3.47.0_linux_amd64.tar.gz"
      sha256 "5754c7350c6ca3d30f29b8f132d590bdb16c487291cefa42ac38f4333fb35156"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.47.0/pipelinectl_3.47.0_linux_arm64.tar.gz"
      sha256 "654439c8c17f9c6a2699c46db0056543b781d768925fbf22b5410443a89ad639"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
