# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3630 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.63.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.63.0/pipelinectl_3.63.0_darwin_all.tar.gz"
    sha256 "e5f41a73777bcd0d83215dd9d7ed82d5cd98d2f0d18f895efa551ff7afe2dca5"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.63.0/pipelinectl_3.63.0_linux_amd64.tar.gz"
      sha256 "7ffc68760bc0cf42beec416a772f8f58b09a4788edc1c06565a1158e32030e7b"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.63.0/pipelinectl_3.63.0_linux_arm64.tar.gz"
      sha256 "506ef32b0568c0559fa357105fedce6f72cd96b06c5970cf24b3e11f2a4bebb2"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
