# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.67.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.67.0/pipelinectl_3.67.0_darwin_all.tar.gz"
    sha256 "58f5dee9f2b984e561dffd4bb50b26a5c9495177531379b8d7b70c118c9096a3"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.67.0/pipelinectl_3.67.0_linux_amd64.tar.gz"
      sha256 "67aae847cc9323b87382ee1dc0bcf3e9e21bebdc14d485c6a0af88e262c3dce7"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.67.0/pipelinectl_3.67.0_linux_arm64.tar.gz"
      sha256 "38dab79187ed67b855e2132eee3d7608b1680f4a38ed1c6cb717d841610a4802"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
