# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3300 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.30.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.30.0/pipelinectl_3.30.0_darwin_all.tar.gz"
    sha256 "b6b0c1444ffd4c42a3481a47240f8c0de45eb9aa808adbade2f197d8aec8a9c9"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.30.0/pipelinectl_3.30.0_linux_amd64.tar.gz"
        sha256 "73cdf84e9967d4f5865279a2cdcec6a8be77d01c7b3e2954045a14bd6ebdf8ed"

        def install
          bin.install "pipelinectl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.30.0/pipelinectl_3.30.0_linux_arm64.tar.gz"
        sha256 "693a5f6f501735a3166462d4e5bec0f75b95935e2eaeb482d2a3881fa0ff7477"

        def install
          bin.install "pipelinectl"
        end
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
