# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3680 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.68.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.68.0/pipelinectl_3.68.0_darwin_all.tar.gz"
    sha256 "28c2ee653ca2414da55abf63367e6893f58728c68ff7fc9680386b43ed6b1013"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.68.0/pipelinectl_3.68.0_linux_amd64.tar.gz"
      sha256 "7a0015b104ee2362802f2b01a3d3387c81616b9d6a25fdb49c38d24e7ad8baff"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.68.0/pipelinectl_3.68.0_linux_arm64.tar.gz"
      sha256 "c25ade88f3c0e73a869b3b04f2d20c998793ae46ed5baa09f7e65fc9c09972ea"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
