# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipelinectlAT3340 < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.34.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.34.0/pipelinectl_3.34.0_darwin_all.tar.gz"
    sha256 "53cd225253055e767026b55854c7d7cb4a3a7703bdc59b4a6b0d93b50745ea2b"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.34.0/pipelinectl_3.34.0_linux_amd64.tar.gz"
        sha256 "c963809656313b7316923f0b6d2351907b65223d0f377adb59e66922ca9a758c"

        def install
          bin.install "pipelinectl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.34.0/pipelinectl_3.34.0_linux_arm64.tar.gz"
        sha256 "abb6243bc04717457a731a54b0610b42497489c50c97fecb3d4cee4a8db49401"

        def install
          bin.install "pipelinectl"
        end
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
