# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipelinectl < Formula
  desc "Chronosphere Telemetry Pipelines CLI"
  homepage "https://docs.chronosphere.io/pipeline-cli"
  version "3.64.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.64.0/pipelinectl_3.64.0_darwin_all.tar.gz"
    sha256 "653d862eed4ce403c950706eca290558682c0b40383ce8bbb99d11d2fe48ccca"

    def install
      bin.install "pipelinectl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.64.0/pipelinectl_3.64.0_linux_amd64.tar.gz"
      sha256 "09da03672a024b3751e814e9498bc1bdae5991395718d9db71de3d4402b5bfff"
      def install
        bin.install "pipelinectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chronosphereio/calyptia-cli/releases/download/v3.64.0/pipelinectl_3.64.0_linux_arm64.tar.gz"
      sha256 "67fc251eefa579fd0a11a7012682b09c117c2fc6a793ff2ee3266f1d86dfd893"
      def install
        bin.install "pipelinectl"
      end
    end
  end

  test do
    system "#{bin}/pipelinectl version"
  end
end
